### ISSUE TITLE
error when i create

### ISSUE THREAD

**Issue by codesaz** [shyim/teamspeak-manager#2]
/usr/lib/node_modules/teamspeak-manager/src/Command/ListTeamspeakCommand.js:14
            result.forEach(async folder => {
                           ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/teamspeak-manager/index.js:22:52)

**Comment by shyim** [comment]
Which node version are you using

**Comment by codesaz** [comment]
> Which node version are you using

node -v 
v10.16.3

Do you think its better for me to use older versions?
pls help me
